name: woii121(""") 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: honor 8x
      run: unlockimei
    - name: make checkn 
      run: make check
    - name: make distcheck
      run: make distcheck
